// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkdbzgasphacukxjqpbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZGJ6Z2FzcGhhY3VreGpxcGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMTk3NDksImV4cCI6MjA4NDY5NTc0OX0.m0ADIXorPMJZj9HaZS0xP6corcjuoJBH2YZSQpVAoxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});